// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdewrrdxlvksbflasevr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZXdycmR4bHZrc2JmbGFzZXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjUzNjgsImV4cCI6MjA3Mzg0MTM2OH0.qAe7Jl9SzfomGN0p5Xaqcq1TobDYzXmf0vtza6NWyBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});